### ISSUE TITLE
literm ddo f/x support?

### ISSUE THREAD

**Issue by ryanfantus** [mkrueger/icy_tools#10]
Would it be possible to add DDO F/X support to play the locatha games? I could never get the actual literm client to work and have never been able to play these games, it's been on my bucket list for a long time.

**Comment by mkrueger** [comment]
I searched for that I don't think that the DDO F/X license allows that unfortunately. I'm not sure about the extend of the patent/copyright situation there but their license is problematic in most parts of the world.

**Comment by ryanfantus** [comment]
Ah that's a bummer. It's really unfortunate as there's no way to even use the literm client in DosBox, it's useless lol.
