### ISSUE TITLE
icyterm mac arm no ripscript option/support?

### ISSUE THREAD

**Issue by ryanfantus** [mkrueger/icy_tools#11]
I can't figure out how to enable ripscript support in the client for Mac (btw I'm using it on Apple Silicon/ARM - is this running natively?)

I have the other terminal options as far as I can tell, ansi, ascii, petscii, etc., but there's no rip option.

**Comment by mkrueger** [comment]
Set terminal type to "RIPscrip" and Screen mode to "RIPscrip" should work.

Which version are you using?

**Comment by mkrueger** [comment]
Works for me - as said set ripscrip terminal type & screen mode.

(Which I should maybe just 1 combo box - next ui overhaul will have linked screen modes, some doesn't make sense stand alone).
