### ISSUE TITLE
Can't connect to mystic systems...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#12]
They use cbc64, cbc128 and cbc256 I believe.  I'm not sure exactly which one.  I had to loosen my ssh servers security a bit to allow netrunner to connect as well.

**Comment by mkrueger** [comment]
It's atm a problem with my ssh layer. I switched the library the new one only supports ciphers that mystic don't. 
However I can connect to your BBS with ssh.

I wanted to look at that last week but got distracted by the work on compression algorithms :/

**Comment by mkrueger** [comment]
Looked into it today. It's not so easy as I thought. There are just 2 async ssh libs and I already use the 'better' one. But it's missing many key exchange algorithms. Esp. the older/more common ones.

**Comment by mkrueger** [comment]
Releasing today -  at least enigma bbs compatible key exchange got added.

ps. this is the library I currently use:  https://github.com/warp-tech/russh

It's atm the best tokio lib for ssh unfortunately some key exchange is missing for mystic - needs to get added to russh.  It's still in active development so I assume that mystic key exchange will get added at some point.

**Comment by mkrueger** [comment]
Fixed ssh in 0.7.9
