### ISSUE TITLE
IcyTerm 7.7 crash update

### ISSUE THREAD

**Issue by skipper1947** [mkrueger/icy_tools#15]
Sorry, cant find my original post on the topic of crash with "ERROR - run_update_thread::read_data:"  log message. Anyway, I found if I change the protocol from Telnet to Raw, it works OK. Don't know what that is about as it has always been set to Telnet in previous versions.

**Comment by mkrueger** [comment]
Updated the builds - should work now.

**Comment by skipper1947** [comment]
Works great, thanks for your work! :)
