### ISSUE TITLE
Icyterm won't start...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#16]
I've tried redownloading it and putting it in various locations, and it did work at first, but now when I double click on the executable, nothing happens. .7.6 works fine.

**Comment by mkrueger** [comment]
Is there anything in the log file?

help->terminal->open settings dir -> icy_term.log

(Should work with 7.6 to open the log file). The only thing that's changed is that "skypix" got added - can't imagine that this breaks something. However the log may contain the answer.

I've been using 7.7 now several days - seems to work. Which OS are you on?

**Comment by martykazmaier** [comment]
Windows.
INFO - Starting iCY TERM 0.7.7
INFO - Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
INFO - Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
INFO - shutting down.
INFO - Starting iCY TERM 0.7.7
INFO - Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
INFO - Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
INFO - Starting iCY TERM 0.7.7
INFO - Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
INFO - Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
INFO - shutting down.
INFO - shutting down.
INFO - Starting iCY TERM 0.7.7
INFO - Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
INFO - Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
ERROR - run_update_thread::read_data: Connection aborted
INFO - shutting down.
________________________________

**Comment by martykazmaier** [comment]
No log entries at all.
________________________________

**Comment by mkrueger** [comment]
tested the 0.7.7 build - not much of an issue. 

When you rename or move the settings file (don't delete it) does it work?

**Comment by martykazmaier** [comment]
I don't see a settings file, what should I look for?
________________________________

**Comment by martykazmaier** [comment]
Nevermind, used everything to find icy_term.exe and then checked properties for the location. After renaming the setting file it works!
________________________________

**Comment by mkrueger** [comment]
Then there is something in the settings which caused it. Which is bad :/. I'll review the loading code.

**Comment by mkrueger** [comment]
I've reviewed the loading code and made it more stable. That might fix that issue.
