### ISSUE TITLE
Icyterm bugs...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#2]
1.  After a download is completed, the external server doesn't seem to
respond to input, but the keystrokes are displayed on my system.

2. If more than one key is pressed at a time (like ctrl or shift and arrow
keys), the input isn't processed.

3.  downloads don't start automatically.  If I'm fullscreen, I have to hit
f11 then the download button.

4.  Embedded links no longer open a browser.

**Comment by mkrueger** [comment]
y saw some issues - I need to rework the ui code a bit. The UI lib got some updates and some of these changes had side effects :/. 
I'll update the protocol code soon that will fix the dl/ul issues and some more things.

**Comment by mkrueger** [comment]
Should be fixed with icy term 0.7.5
