### ISSUE TITLE
Enter handling in Windows...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#20]
This is weird.  If I try to log in manually, after hitting enter, a cr/lf combo seems to be sent instead of just one.  This causes some particularly undesired effects...  Some parts of the board interpret it as two enters.  Sometimes this skips over menu items.

Marty

mostly noticed with telnet at telnet://shsbbs.net:23  (I noticed that optional port numbers are no longer available, it's mandatory.

**Comment by mkrueger** [comment]
Can't find the issue - it may've been a bug in an older version - sounds a bit like it could've happen in the ui lib. Checked with the latest egui (0.28.1) only sends a single #13.

Reopen if it happens again - may be the windows version? I've tested on win 11.
