### ISSUE TITLE
icy_view missing from this repo

### ISSUE THREAD

**Issue by cracklejoy** [mkrueger/icy_tools#21]
I don't seem to see the windows version of icy_view in this release url https://github.com/mkrueger/icy_tools/releases/tag/0.0.1
I assume it's a simple mistake of not copying the portable and setup release from here https://github.com/mkrueger/icy_view/releases

**Comment by mkrueger** [comment]
Updated:
https://github.com/mkrueger/icy_tools/releases/tag/0.0.1

I need to work on icy view/draw for own releases - throwing everything in one tag is just a short term solution :/
