### ISSUE TITLE
[Feature Request] Selection Tools in Icy Draw

### ISSUE THREAD

**Issue by livejamie** [mkrueger/icy_tools#22]
Hello I love the work you've done with Icy Draw.

I know as an ANSI Artist one of the most widely used featiures is the "selection" tools which has been a feature of most drawing tools even going back to TheDraw/AcidDraw.

![image](https://github.com/mkrueger/icy_tools/assets/49513/b88ec7b8-b927-451a-88c5-3d9c52a20847)

Being able to select blocks and move them, stamp, flip, move elements underneath and making them transparent, etc.

These are invaluable tools to any ANSI artist and I'd love to see them implemented in your program! :)

**Comment by mkrueger** [comment]
It has a wide range of selection tools - you can even select by char, non rectangular selections and so on.
So I don't know what's missing.

Just "select" and use cut / paste. You can create new layers, move them around.

There is a selection tool that allows you to select by chars/attribute. If you hit shift while selecting with the selection tool it adds to the selection. ctrl removes from the selection.

If you paste you get options for rotate/x/y/stamp and so on.

**Comment by livejamie** [comment]
Thanks for the quick response! Yes the selection tools you have in place are dope that's why I'm making this request.

Here's a quick screencap showing the Move functionality (M) 

![NVIDIA_Overlay_49TRYdpoe3](https://github.com/mkrueger/icy_tools/assets/49513/7f2986e6-b65d-4d35-92e7-bda1d11a534c)

It helps to have a visual representation of your selection. Move it around the campus to get a preview of what it would look like and place it where it needs to go.

Setting the selected block to go underneath elements or be transparent, as I show in that screencast with the letters layering underneath each other, saves a _ton_ of time.

I also know artists frequently use this block selection's "Stamp" functionality to save time.

I remember you saying that you don't do much drawing yourself, so I'm providing feedback based on a feature I use all the time and wouldn't be able to switch without. I am confident other old sceneheads would feel the same way.

This feature isn't unique to modern editors; it's been a standard since AcidDraw.

Right now you have cut/copy/paste which is fine but not as precise and involves a lot of trial and error/guess work.

**Comment by livejamie** [comment]
Another example for context

![Uploading Moebius_TMq6NCsLuX.gif…]()

**Comment by mkrueger** [comment]
As said - it's a cut & paste thing in icy draw - here a demo that shows some bits and non rectangular selections:

https://github.com/mkrueger/icy_tools/assets/341098/acbd3314-f318-4ec2-9b4b-f4d661bbd40a

**Comment by mkrueger** [comment]
Or you can use selection to replace chars:

https://github.com/mkrueger/icy_tools/assets/341098/1d5d6fa9-72f6-4b1c-83e1-c92e21477e3a

**Comment by livejamie** [comment]
That's interesting. I don't have the same functionality as you. The keyboard shortcuts don't work on Windows 11 Pro for me. Can you help me troubleshoot that?

A few selection questions:
- What's the difference between a yellow and white dotted line selection?
- How do I deselect this yellow dashed area? 

![image](https://github.com/mkrueger/icy_tools/assets/49513/3d37e8ff-59b0-4eed-8073-c8a491753951)

**Comment by mkrueger** [comment]
Y hotkeys are broken atm - I need to fix that. Some update in one of the libs I use seem to have broken them. I need to look if it got fixed.

The yellow thing is the border of the layer you're on. There is an option in the view menu to deactivate that. But I think it's useful when working with layers.

**Comment by mkrueger** [comment]
Closing -> no response. Selection tool is part of icy draw. If there is an issue with it reopen.

**Comment by livejamie** [comment]
I was waiting to respond when hotkeys were fixed, is that done now?
