### ISSUE TITLE
iemsi login disabled, but it still tries...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#23]
With net2bbs, ssh and websocket connections disconnect when using iemsi logins.  I've tried turning it off in the bbs and in the settings, but it still tries and ends up disconnecting.  shsbbs.net:8080 and shsbbs.net:22.  Telnet works fine.

**Comment by martykazmaier** [comment]
iemsi should be able to be disabled entirely if needed.

**Comment by mkrueger** [comment]
should be fixed in 0.7.8
