### ISSUE TITLE
0.7.8 Mac - RIPScrip not appearing as expected

### ISSUE THREAD

**Issue by ryanfantus** [mkrueger/icy_tools#26]
Hi, I set an option to connect to a RIP enabled BBS to use RIP as the Terminal Type. When I connected, it appeared that the initial handshake to determine RIP capabilities succeeded. However, following that, it looks like no RIP was displayed, but instead some garbage which I assume is raw RIPScrip files.

Thanks
<img width="1287" alt="Screenshot 2024-08-23 at 2 16 16 PM" src="https://github.com/user-attachments/assets/c9d25b60-208f-4059-9390-2757f984dc4a">

**Comment by mkrueger** [comment]
You've to set the screen mode to "RIPscrip" as well. UNfortunately it's a 2 stage setting.
Need to change that at some point - next time I update the UI.
