### ISSUE TITLE
.7.8 zmodem broken?

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#28]
I've been unable to download via zmodem (at least sexyz and sexyz 8k) in the latest version under windows.  You can test at shsbbs.net, however you want to connect... I can transfer fine with netrunner.

Marty

**Comment by mkrueger** [comment]
Works for me with telnet. Have issues to connect with ssh atm

Did you use telnet or another protocol for using zmodem?

**Comment by martykazmaier** [comment]
Ok, it appears to be working now.  My results were spotty and reliant on the zmodem protocol used.

**Comment by mkrueger** [comment]
ZModem should be more stable on 0.7.8+
