### ISSUE TITLE
Non-Mystic SSH Issues...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#31]
My Mystic is only for a telnet shiv to get from ssh to telnet (and telnet via geoblocking to telnet).  Conchaos is a synchronet BBS and when I'm on there for a few minutes, it becomes unresponsive and it appears that Icy_Term has disconnected.  Same on my system.  This doesn't have anything to do with the Mystic SSH key issues.

**Comment by codefenix-ConChaos** [comment]
I can corroborate @martykazmaier's statement. With every Sync board I've tried, IcyTerm randomly drops carrier. Repeatable whether using telnet or SSH.

**Comment by mkrueger** [comment]
Haven't seen it it local builds. SSH should work in 0.7.9 - all features of ssh I need are implemented. Not sure if the lib is compatible now to all SSH implementations but at l east mystic works now.

I let the bug open for further investigations. I'll use 0.7.9 a bit longer maybe I can find something.
Are you working on windows? That may be an issue - will try to find something there. Windows tcp stack seems to be slightly different than the linux/mac one. Maybe I'm missing a setting there - will take a look.

**Comment by codefenix-ConChaos** [comment]
Telnet in 0.7.9 seems much more stable. I ran it for over 2 hours connected to my Sync board without any carrier drop.

Was not able to get it to connect to my Sync board at all with SSH. On the host side it just says "session establishment failed." On the client side it doesn't give any error or message at all.

Synchronet Terminal Server log:
```
  12/22  12:42:45p  2528 SSH [x.x.x.x] Attaching to Node 1
  12/22  12:42:45p  Node 1 12:42p  Sun Dec 22 2024            Node   1
  12/22  12:42:45p  Node 1 SSH  host [x.x.x.x]
  12/22  12:42:47p  Node 1 2528 SSH [x.x.x.x] session establishment failed
```

Using the Windows IcyTerm 0.7.9 on Windows 10 64-bit.

**Comment by mkrueger** [comment]
Ok found the issue - will release 0.7.10 today.

**Comment by codefenix-ConChaos** [comment]
Still can't get SSH to connect to Synchronet boards. Tried a few different ones.

New error message from the client side (0.7.10 for Windows):

```
Connect to conchaos.synchro.net:22...
Wrong server signature

NO CARRIER
```

Error message does not always appear though. Usually the screen stays black.
