### ISSUE TITLE
Issue with IcyTerm on Apple M1 (Crash from version 0.7.6)

### ISSUE THREAD

**Issue by IRoN-cP** [mkrueger/icy_tools#36]
Deutsche Version siehe unten..

Hi mkrueger,

Thank you for your work on IcyTerm – it’s truly a fantastic terminal program! However, I’m encountering an issue with the newer versions on my Apple M1.

Version 0.7.5 works perfectly, but all subsequent versions (from 0.7.6 onward) crash immediately upon startup. A crash report is generated, but it’s so cryptic that I can’t make any sense of it.

I’ve attached the crash report below, hoping it might help you analyze the problem. If you need additional information from me or want me to test something, please don’t hesitate to let me know!

Thank you in advance for your support.

Regards, IRoN, Sysop of the Crazy Paradise BBS

Deutsch:

Hallo mkrueger,

vielen Dank für deine Arbeit an IcyTerm – es ist wirklich ein großartiges Terminalprogramm! Ich habe jedoch ein Problem mit den neueren Versionen auf meinem Apple M1.

Die Version 0.7.5 funktioniert einwandfrei, aber alle Versionen danach (ab 0.7.6) führen zu einem sofortigen Absturz beim Starten. Es erscheint ein Fehlerbericht, aber der ist leider so kryptisch, dass ich damit nicht wirklich etwas anfangen kann.

Ich habe den Fehlerbericht unten angehängt, in der Hoffnung, dass er dir bei der Analyse weiterhilft. Falls du weitere Informationen von mir benötigst oder ich etwas testen soll, lass es mich bitte wissen!

Vielen Dank im Voraus für deine Unterstützung.

Grüsse, IRoN Sysop der Crazy Paradise BBS.

---------------- ( Report ) --------

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               icy_term [36170]
Path:                  /private/var/folders/*/icy_term.app/Contents/MacOS/icy_term
Identifier:            github.com.icy_term
Version:               0.1.0 (???)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-12-20 17:36:44.9241 +0100
OS Version:            macOS 15.2 (24C101)
Report Version:        12
Anonymous UUID:        7702D666-1F35-178B-3E97-D0357B32652E

Sleep/Wake UUID:       61BDDBA1-E5FD-477E-8C0F-D6FEB3807211

Time Awake Since Boot: 330000 seconds
Time Since Wake:       329044 seconds

System Integrity Protection: enabled

Crashed Thread:        0  main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   icy_term [36170]

Application Specific Information:
abort() called

Thread 0 Crashed:: main Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1813c3720 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1813fbf70 pthread_kill + 288
2   libsystem_c.dylib             	       0x181308908 abort + 128
3   icy_term                      	       0x1044948f0 0x104298000 + 2083056
4   icy_term                      	       0x1044948e4 0x104298000 + 2083044
5   icy_term                      	       0x1045c8494 0x104298000 + 3343508
6   icy_term                      	       0x1045cbdfc 0x104298000 + 3358204
7   icy_term                      	       0x1045cb848 0x104298000 + 3356744
8   icy_term                      	       0x1045cb7b0 0x104298000 + 3356592
9   icy_term                      	       0x1045cb7a4 0x104298000 + 3356580
10  icy_term                      	       0x1046c3db8 0x104298000 + 4373944
11  icy_term                      	       0x1046c3e14 0x104298000 + 4374036
12  icy_term                      	       0x10462fa3c 0x104298000 + 3766844
13  icy_term                      	       0x1042e14f0 0x104298000 + 300272
14  icy_term                      	       0x1042e644c 0x104298000 + 320588
15  icy_term                      	       0x1042a3508 0x104298000 + 46344
16  icy_term                      	       0x1042ea7d4 0x104298000 + 337876
17  dyld                          	       0x18107c274 start + 2840

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000002   x6: 0x0000000000000031   x7: 0x0000000000000001
    x8: 0xa3ae433e5e6a1ac0   x9: 0xa3ae433fb4a7d880  x10: 0x0000000000000000  x11: 0x0000000000110000
   x12: 0x000000016bb65659  x13: 0x000060000312801e  x14: 0x00000000fffffff2  x15: 0x000000016bb65908
   x16: 0x0000000000000148  x17: 0x00000001f330ecb0  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x00000001eacdc320  x22: 0x0000000000000001  x23: 0x00000001046db2da
   x24: 0x0000000400000001  x25: 0x00000001046db205  x26: 0x00000001046db20c  x27: 0x00000001456063f0
   x28: 0x000000016bb67537   fp: 0x000000016bb65a70   lr: 0x00000001813fbf70
    sp: 0x000000016bb65a50   pc: 0x00000001813c3720 cpsr: 0x40001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x104298000 -        0x104c03fff github.com.icy_term (0.1.0) <7541c254-90cd-3a18-b99e-7b79c150c687> /private/var/folders/*/icy_term.app/Contents/MacOS/icy_term
       0x1813ba000 -        0x1813f4ff7 libsystem_kernel.dylib (*) <dfc9530c-e75b-3d1c-a9a6-85c8a709d6a7> /usr/lib/system/libsystem_kernel.dylib
       0x1813f5000 -        0x181401fff libsystem_pthread.dylib (*) <f1661613-b1c8-320d-b69d-97f174130e29> /usr/lib/system/libsystem_pthread.dylib
       0x18128f000 -        0x181310ffb libsystem_c.dylib (*) <67989e50-e562-3062-9ff9-44bd90648e66> /usr/lib/system/libsystem_c.dylib
       0x181076000 -        0x1810f7f3f dyld (*) <4ce86d18-f3fa-3d2a-a1b8-e7cd8a52fb0d> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=893.4M resident=0K(0%) swapped_out_or_unallocated=893.4M(100%)
Writable regions: Total=538.5M written=257K(0%) resident=257K(0%) swapped_out=0K(0%) unallocated=538.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                   32K        1 
MALLOC                           530.2M       13 
MALLOC guard page                   96K        6 
Stack                             8160K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                         32K        2 
VM_ALLOCATE (reserved)             128K        1         reserved VM address space (unallocated)
__AUTH                            1097K      204 
__AUTH_CONST                      18.2M      356 
__DATA                            4605K      338 
__DATA_CONST                      13.6M      359 
__DATA_DIRTY                       692K      110 
__FONT_DATA                        2352        1 
__LINKEDIT                       606.1M        2 
__OBJC_RW                         2373K        1 
__TEXT                           287.3M      373 
__TPRO_CONST                       272K        2 
page table in kernel               257K        1 
shared memory                       32K        1 
===========                     =======  ======= 
TOTAL                              1.5G     1773 
TOTAL, minus reserved VM space     1.5G     1773 

-----------
Full Report
-----------

{"app_name":"icy_term","timestamp":"2024-12-20 17:36:45.00 +0100","app_version":"0.1.0","slice_uuid":"7541c254-90cd-3a18-b99e-7b79c150c687","build_version":"","platform":1,"bundleID":"github.com.icy_term","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 15.2 (24C101)","roots_installed":0,"name":"icy_term","incident_id":"9AD72CF2-FEA1-4E58-A1D2-3EE6929D9676"}
{
  "uptime" : 330000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "coalitionID" : 21521,
  "osVersion" : {
    "train" : "macOS 15.2",
    "build" : "24C101",
    "releaseType" : "User"
  },
  "captureTime" : "2024-12-20 17:36:44.9241 +0100",
  "codeSigningMonitor" : 1,
  "incident" : "9AD72CF2-FEA1-4E58-A1D2-3EE6929D9676",
  "pid" : 36170,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-12-20 17:36:40.2692 +0100",
  "procStartAbsTime" : 8006084686692,
  "procExitAbsTime" : 8006196394059,
  "procName" : "icy_term",
  "procPath" : "\/private\/var\/folders\/*\/icy_term.app\/Contents\/MacOS\/icy_term",
  "bundleInfo" : {"CFBundleShortVersionString":"0.1.0","CFBundleIdentifier":"github.com.icy_term"},
  "storeInfo" : {"deviceIdentifierForVendor":"0910B4AF-3F84-52A7-A5E2-6F05F0E89BCC","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "github.com.icy_term",
  "crashReporterKey" : "7702D666-1F35-178B-3E97-D0357B32652E",
  "codeSigningID" : "icy_term-7bd0b4565847661a",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570556929,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"fyMD1f17v6n9AwCRcuD\/l78DAJH9e8Go\/w9f1sADX9YQKYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkWfg\/5e\/AwCR\/XvBqP8PX9bAA1\/WcAqA0g=="},
  "bootSessionUUID" : "EB6BC7BF-9E1B-40FD-BB19-826FDDE26DB6",
  "wakeTime" : 329044,
  "sleepWakeUUID" : "61BDDBA1-E5FD-477E-8C0F-D6FEB3807211",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"icy_term","byPid":36170},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":2},{"value":49},{"value":1},{"value":11794438409280953024},{"value":11794438415022807168},{"value":0},{"value":1114112},{"value":6102079065},{"value":105553167810590},{"value":4294967282},{"value":6102079752},{"value":328},{"value":8375037104},{"value":0},{"value":6},{"value":259},{"value":8234320672,"symbolLocation":224,"symbol":"_main_thread"},{"value":1},{"value":4369265370},{"value":17179869185},{"value":4369265157},{"value":4369265164},{"value":5458912240},{"value":6102086967}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6463405936},"cpsr":{"value":1073745920},"fp":{"value":6102080112},"sp":{"value":6102080080},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6463174432,"matchesCrashFrame":1},"far":{"value":0}},"id":39073280,"triggered":true,"name":"main","queue":"com.apple.main-thread","frames":[{"imageOffset":38688,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":1},{"imageOffset":28528,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":2},{"imageOffset":497928,"symbol":"abort","symbolLocation":128,"imageIndex":3},{"imageOffset":2083056,"imageIndex":0},{"imageOffset":2083044,"imageIndex":0},{"imageOffset":3343508,"imageIndex":0},{"imageOffset":3358204,"imageIndex":0},{"imageOffset":3356744,"imageIndex":0},{"imageOffset":3356592,"imageIndex":0},{"imageOffset":3356580,"imageIndex":0},{"imageOffset":4373944,"imageIndex":0},{"imageOffset":4374036,"imageIndex":0},{"imageOffset":3766844,"imageIndex":0},{"imageOffset":300272,"imageIndex":0},{"imageOffset":320588,"imageIndex":0},{"imageOffset":46344,"imageIndex":0},{"imageOffset":337876,"imageIndex":0},{"imageOffset":25204,"symbol":"start","symbolLocation":2840,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4364795904,
    "CFBundleShortVersionString" : "0.1.0",
    "CFBundleIdentifier" : "github.com.icy_term",
    "size" : 9879552,
    "uuid" : "7541c254-90cd-3a18-b99e-7b79c150c687",
    "path" : "\/private\/var\/folders\/*\/icy_term.app\/Contents\/MacOS\/icy_term",
    "name" : "icy_term"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6463135744,
    "size" : 241656,
    "uuid" : "dfc9530c-e75b-3d1c-a9a6-85c8a709d6a7",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6463377408,
    "size" : 53248,
    "uuid" : "f1661613-b1c8-320d-b69d-97f174130e29",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6461911040,
    "size" : 532476,
    "uuid" : "67989e50-e562-3062-9ff9-44bd90648e66",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6459711488,
    "size" : 532288,
    "uuid" : "4ce86d18-f3fa-3d2a-a1b8-e7cd8a52fb0d",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6458900480,
  "size" : 4861722624,
  "uuid" : "e36100c7-89e7-3970-8938-8483ccd7019a"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=893.4M resident=0K(0%) swapped_out_or_unallocated=893.4M(100%)\nWritable regions: Total=538.5M written=257K(0%) resident=257K(0%) swapped_out=0K(0%) unallocated=538.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nKernel Alloc Once                   32K        1 \nMALLOC                           530.2M       13 \nMALLOC guard page                   96K        6 \nStack                             8160K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                         32K        2 \nVM_ALLOCATE (reserved)             128K        1         reserved VM address space (unallocated)\n__AUTH                            1097K      204 \n__AUTH_CONST                      18.2M      356 \n__DATA                            4605K      338 \n__DATA_CONST                      13.6M      359 \n__DATA_DIRTY                       692K      110 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       606.1M        2 \n__OBJC_RW                         2373K        1 \n__TEXT                           287.3M      373 \n__TPRO_CONST                       272K        2 \npage table in kernel               257K        1 \nshared memory                       32K        1 \n===========                     =======  ======= \nTOTAL                              1.5G     1773 \nTOTAL, minus reserved VM space     1.5G     1773 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "main",
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "2ebc035820baa3990fc35046eb70ff8bfeb7f52a",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "654439cdafbf5b61207873a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000004
    },
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {

      },
      "deploymentId" : 240000010
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000007
    }
  ]
}
}

Model: MacBookPro18,3, BootROM 11881.61.3, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In

**Comment by mkrueger** [comment]
Denke ich habe ein Problem gefunden - dachte ist der build. Werde heute eine bugfix runde einlegen - 0.7.9 sollte laufen.
