### ISSUE TITLE
Crashes immediately...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#37]
Upon trying to connect to my websocket at port 999 at shsbbs.net.

**Comment by mkrueger** [comment]
Websocket lib required a pre initialization call - I've drafted a new release. However can't connect to shsbbs.net:999.

It doesn't crash and websocket connection to xibalba now works. is this a secure or non secure connection? How do you test the websocket connection (without icyterm)?

Released here: 
https://github.com/mkrueger/icy_tools/releases/tag/IcyTerm0.7.10

**Comment by martykazmaier** [comment]
Secure.  I can connect via ftelnet and this websocket. I can connect via port 999 and .7.7 no problem.

________________________________

**Comment by mkrueger** [comment]
Can't connect with shsbbs using ftelnet :/.

Have you tried 0.7.10?

**Comment by martykazmaier** [comment]
I have and it works.  I have users connecting using the ftelnet widget on https://shsbbs.net/bbs.html as well.  Your ip may be blocked.  What country are you in?  I'll try refreshing my block list on my pfsense box.

________________________________

**Comment by martykazmaier** [comment]
I'm blocking Iran, North and South Korea, Russia and China.  Do you have a static IP? I could put you in whitelist.

________________________________

**Comment by mkrueger** [comment]
Thought so - I tried several regions with vpn. But I've no chance reaching  https://shsbbs.net/bbs.html
