### ISSUE TITLE
Buggy rendering of some NFOs?

### ISSUE THREAD

**Issue by BackSpace54** [mkrueger/icy_tools#39]
Hi,
i've two NFO files that render badly in ICY Tools but look correct in NFOPad (see screenshots).
Is there a special option to render these correctly? (NFOs attached)
Thanks.
<img width="1206" alt="NFOPad_bTyjQfVCNB" src="https://github.com/user-attachments/assets/cb806899-8f1d-4c1f-941e-8b6ca9b83cff" />
<img width="1205" alt="NFOPad_oeM9qf19bA" src="https://github.com/user-attachments/assets/75c15051-1ef5-47a0-b447-c23c36c329a9" />
[Nfo.zip](https://github.com/user-attachments/files/18240426/Nfo.zip)

**Comment by mkrueger** [comment]
Embarrassing :/ didn't handle the tab char correctly :/.  Will update icy view/draw when the build finishes.
