### ISSUE TITLE
Can't install Linux version...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#4]
error: failed to select a version for `env_logger`.
    ... required by package `icy_view_gui v0.2.2 (/home/shurato/Downloads/icy_tools-IcyTerm0.7.5/crates/icy_view_gui)`
    ... which satisfies path dependency `icy_view_gui` of package `icy_draw v0.3.0 (/home/shurato/Downloads/icy_tools-IcyTerm0.7.5/crates/icy_draw)`
versions that meet the requirements `^0.11.1` are: 0.11.3, 0.11.2, 0.11.1

the package `icy_view_gui` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

failed to select a version for `env_logger` which could resolve this conflict

after "sudo crate run --bin icy_term"

I thought I had all of the dependencies installed.  I'm more of a Windows user, but I thought I'd see if I could replicate the dogworld ][ bug on my system in Linux.

**Comment by mkrueger** [comment]
I've just updated the .deb files - can you try if these work ?

Not sure about the env_logger issue - I've changed the version number should now more gentle between the 0.11.x versions. But they did use the same. I'll look at the windows version - I'm just busy with icy_board atm.

**Comment by mkrueger** [comment]
![grafik](https://github.com/mkrueger/icy_tools/assets/341098/1fd8b6c3-8fb6-4ae7-8643-8792ad640a58)

works for me on windows as well :/ - I hate if that happens. And nothing in the log files?
I assumed that there may be a stream in block mode that may lock  but that can only happen in one protocol - and not all :/.

**Comment by martykazmaier** [comment]
I'm still getting an error that the package can't find the env_logger version.  Using debian 12.
________________________________
