### ISSUE TITLE
icy_term 0.75 not running upon click on macOS Ventura 13.6.6

### ISSUE THREAD

**Issue by BitSavage** [mkrueger/icy_tools#5]
Version: macOS Ventura 13.6.6
Icy Term: 0.75

Replication steps
1. Install from DMG (open DMG and drag/drop to Applications folder)
2. Go to Applications and click on it to run.
3. Dialog appears.
You can't use this version of application "icy_term" with this version of MacOS.
Expected: To Run Icy Term :)

If you do Show Package Contents on icy_term and CD to Contents -> MacOS.  Click on the icy_term executable. It works fine.

Icy Term 0.74 works fine, and IIRC didn't have this issue on install.

One other quick note, when you install Icy Term, the old 0.74 Icy Term is called "Icy Term" whereas of 0.75 it's called "icy_term".  So, it will not overwrite the old version (aka replace.). Minor cleanup but does do a second install.

**Comment by mkrueger** [comment]
Seems "macos-latest" build target on github is macOS Sonoma. I changed the build script so that it produces universal .dmg files.

I changed it to macos-13 - I'll update the 0.7.6 files when the build finishes.

**Comment by mkrueger** [comment]
So I've updated the 0.7.6 builds. They work for me however I've to acceppt some security nag screen in the options to make it run.

But that was always the case for me.

**Comment by mkrueger** [comment]
Didn't fix the part with the "Icy Term" name - have tried it today but for some reason the new build script fails somewhere. Didn't find the issue. 

But I accept changes here if it's really important. Given how easy it is to remove icy term from mac it's not a big thing. However "icy_term" is a very bad .app name.
