### ISSUE TITLE
BBS type keeps resetting...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#7]
I'm using secure websocket in icyterm, but it keeps resetting to telnet with the 8080 port and won't connect.  Every time I start the program back up, I manually have to change this.  It's annoying, but I'm getting used to it.

**Comment by mkrueger** [comment]
Should be fixed in later (read: current) 0.7.6 builds.

**Comment by mkrueger** [comment]
I released 0.7.6 a bit too early - I fixed some minor issues after the release. 

However SSH is still a problem - I switched the library because of technical reasons. Will release 0.7.7 when I sorted that out.
