### ISSUE TITLE
error from secure websocket connection (shsbbs.net:8080).

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#8]
Target closed
Connection aborted: IO error: peer closed connection without sending TLS close_n
otify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpect
ed-eof

**Comment by mkrueger** [comment]
I switched the secure websocket lib - could likely be that something doesn't work.

(Xibalba secure websocket works however)

I've not settled yet for a websocket library I need to test at least another one. But good to know what to test for.

**Comment by martykazmaier** [comment]
I got that error when closing the connection.  It may have only been once though.
________________________________

**Comment by martykazmaier** [comment]
I'm still getting it if I let the system follow through the logoff ansi and hanging up itself.  Not just once.  Everytime on my system at least.
