### ISSUE TITLE
The previous bug I reported...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#9]
With the error pasted and only the error wasn't intentionally vague.  I'm still getting it when a connection closes normally from a secure websocket connection.

**Comment by martykazmaier** [comment]
Target closed
Connection aborted: IO error: peer closed connection without sending TLS close_n
otify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpect
ed-eof

That error.  It's after the remote system hangs up.  Remember, the BBS doesn't know it's using a web socket, I'm using websockify to transfer a websocket connection to a telnet one.

**Comment by mkrueger** [comment]
Ah ok it's about hangup? I'll take a look. Took me a while to get the dogworld bug fixed - because I thought I know what's going on without reproing it. 

However the communictation layer rework was needed. As badly as the UI rework which I still need to do :/. ATM I've too much on my todo list.

**Comment by mkrueger** [comment]
should be fixed in 0.7.7
